controller_list:
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - finger_joint
  - name: fake_UR5e_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
initial:  # Define initial robot poses.
  - group: gripper
    pose: open
  - group: UR5e
    pose: home